//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlantportaalReEncryptor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67a674bd68a281d117648e1db4a19fcafae61972")]
        public string KeyVaultCertificateThumbprintOntwikkel {
            get {
                return ((string)(this["KeyVaultCertificateThumbprintOntwikkel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3E416BE5BE39EF7A62F0C76D0DDA7AE5C78E79FA")]
        public string KeyVaultCertificateThumbprintAccept {
            get {
                return ((string)(this["KeyVaultCertificateThumbprintAccept"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("718B84C093BEE60932CF680169D95050AACEDBDE")]
        public string KeyVaultCertificateThumbprintProductie {
            get {
                return ((string)(this["KeyVaultCertificateThumbprintProductie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sphdhvdeelnemerdev.vault.azure.net/secrets/SPHDHVDeelnemerKeyDev/740867e4" +
            "8eec4331ae13d9d81541d04a")]
        public string KeyVaultSecrectOld {
            get {
                return ((string)(this["KeyVaultSecrectOld"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sphdhvdeelnemerdev.vault.azure.net/secrets/SPHDHVDeelnemerKeyDev/8a8850b2" +
            "0c764f4ab9ec6ae544000a6c")]
        public string KeyVaultSecrectNew {
            get {
                return ((string)(this["KeyVaultSecrectNew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4bb4eb36-fb4a-4a83-b7e7-e502c07fb84b")]
        public string KeyVaultApplicationId {
            get {
                return ((string)(this["KeyVaultApplicationId"]));
            }
        }
    }
}
