//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icatt.Auditing.Access.AuditTrail.ServiceTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81732dd5-256c-4b50-afa6-54d01e74838f")]
        public string AuditKeyVaultClientId {
            get {
                return ((string)(this["AuditKeyVaultClientId"]));
            }
            set {
                this["AuditKeyVaultClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("430e933f3a11ca44eda086849c4781240a916fb0")]
        public string AuditKeyVaultCertificateThumbprint {
            get {
                return ((string)(this["AuditKeyVaultCertificateThumbprint"]));
            }
            set {
                this["AuditKeyVaultCertificateThumbprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SphdhvKlantPortaalAuditKeyDEV")]
        public string AuditKeyVaultAuditSecret {
            get {
                return ((string)(this["AuditKeyVaultAuditSecret"]));
            }
            set {
                this["AuditKeyVaultAuditSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2d653730-33a8-4ee4-8be6-65b9addac6df")]
        public string AuditKeyVaultTenantId {
            get {
                return ((string)(this["AuditKeyVaultTenantId"]));
            }
            set {
                this["AuditKeyVaultTenantId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sphdhvauditdev.vault.azure.net/")]
        public string AuditKeyVaultUrl {
            get {
                return ((string)(this["AuditKeyVaultUrl"]));
            }
            set {
                this["AuditKeyVaultUrl"] = value;
            }
        }
    }
}
